### ISSUE TITLE
Update README with a pointer to a more recent template

### ISSUE THREAD

**Issue by jessmartin** [zapnap/sinatra-template#7]
Yo @zapnap! I come across this repo from time to time when searching for a template to start a Sinatra app. It's pretty high in the google results.

You should think about adding a line at the top of the README to redirect to a more recent template.

Just a thought! I'll drop a link here if I find a good one that I like.

:smile:

**Comment by jessmartin** [comment]
Ugh. No single-shot solution for this that I can find. The problem seems to be that everyone starts a Sinatra app with a different end-goal (basic app, API, blog, etc) and therefore the starter apps diverge significantly.

**Comment by zapnap** [comment]
Yeah it's tricky. Micro-frameworks are usable for so many different things that it's difficult to nail down one general-use template for building apps. This project is admittedly out of date and I'd be happy to maintain a list of alternative more-recently-updated options in the README if someone wants to send a pull request.

**Comment by zapnap** [comment]
btw I updated it this week so it should be a bit more modern :)
